-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation multiParamPathParam
module OpenAPI.Operations.MultiParamPathParam where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Decoding
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Either as GHC.Internal.Data.Either
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified OpenAPI.Common
import OpenAPI.Types

-- | > GET /pet/multiparam2/{status}
-- 
-- Operation with multiple parameters (some from path params)
multiParamPathParam :: forall m . OpenAPI.Common.MonadHTTP m => MultiParamPathParamParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> OpenAPI.Common.ClientT m (Network.HTTP.Client.Types.Response MultiParamPathParamResponse) -- ^ Monadic computation which returns the result of the operation
multiParamPathParam parameters = GHC.Base.fmap (\response_0 -> GHC.Base.fmap (Data.Either.either MultiParamPathParamResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> MultiParamPathParamResponse200 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either GHC.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                           Dog)
                                                                                                                                                                               | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0) (OpenAPI.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.Internal.pack "GET") ("/pet/multiparam2/" GHC.Base.<> (OpenAPI.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (OpenAPI.Common.textToByte GHC.Base.$ OpenAPI.Common.stringifyModel (multiParamPathParamParametersPathStatus parameters))) GHC.Base.<> "")) [OpenAPI.Common.QueryParameter (Data.Text.Internal.pack "status") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (multiParamPathParamParametersQueryStatus parameters)) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            OpenAPI.Common.QueryParameter (Data.Text.Internal.pack "filter") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> multiParamPathParamParametersQueryFilter parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            OpenAPI.Common.QueryParameter (Data.Text.Internal.pack "referenceParameter") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (multiParamPathParamParametersQueryReferenceParameter parameters)) (Data.Text.Internal.pack "form") GHC.Types.False])
-- | Defines the object schema located at @paths.\/pet\/multiparam2\/{status}.GET.parameters@ in the specification.
-- 
-- 
data MultiParamPathParamParameters = MultiParamPathParamParameters {
  -- | pathStatus: Represents the parameter named \'status\'
  -- 
  -- Status in path (from path params)
  multiParamPathParamParametersPathStatus :: MultiParamPathParamParametersPathStatus
  -- | queryFilter: Represents the parameter named \'filter\'
  -- 
  -- Filter the entries?
  , multiParamPathParamParametersQueryFilter :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | queryReferenceParameter
  , multiParamPathParamParametersQueryReferenceParameter :: Cat
  -- | queryStatus: Represents the parameter named \'status\'
  -- 
  -- Status in query
  , multiParamPathParamParametersQueryStatus :: MultiParamPathParamParametersQueryStatus
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON MultiParamPathParamParameters
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["pathStatus" Data.Aeson.Types.ToJSON..= multiParamPathParamParametersPathStatus obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryFilter" Data.Aeson.Types.ToJSON..=)) (multiParamPathParamParametersQueryFilter obj) : ["queryReferenceParameter" Data.Aeson.Types.ToJSON..= multiParamPathParamParametersQueryReferenceParameter obj] : ["queryStatus" Data.Aeson.Types.ToJSON..= multiParamPathParamParametersQueryStatus obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["pathStatus" Data.Aeson.Types.ToJSON..= multiParamPathParamParametersPathStatus obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryFilter" Data.Aeson.Types.ToJSON..=)) (multiParamPathParamParametersQueryFilter obj) : ["queryReferenceParameter" Data.Aeson.Types.ToJSON..= multiParamPathParamParametersQueryReferenceParameter obj] : ["queryStatus" Data.Aeson.Types.ToJSON..= multiParamPathParamParametersQueryStatus obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON MultiParamPathParamParameters
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "MultiParamPathParamParameters" (\obj -> (((GHC.Base.pure MultiParamPathParamParameters GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pathStatus")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryFilter")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "queryReferenceParameter")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "queryStatus"))}
-- | Create a new 'MultiParamPathParamParameters' with all required fields.
mkMultiParamPathParamParameters :: MultiParamPathParamParametersPathStatus -- ^ 'multiParamPathParamParametersPathStatus'
  -> Cat -- ^ 'multiParamPathParamParametersQueryReferenceParameter'
  -> MultiParamPathParamParametersQueryStatus -- ^ 'multiParamPathParamParametersQueryStatus'
  -> MultiParamPathParamParameters
mkMultiParamPathParamParameters multiParamPathParamParametersPathStatus multiParamPathParamParametersQueryReferenceParameter multiParamPathParamParametersQueryStatus = MultiParamPathParamParameters{multiParamPathParamParametersPathStatus = multiParamPathParamParametersPathStatus,
                                                                                                                                                                                                      multiParamPathParamParametersQueryFilter = GHC.Maybe.Nothing,
                                                                                                                                                                                                      multiParamPathParamParametersQueryReferenceParameter = multiParamPathParamParametersQueryReferenceParameter,
                                                                                                                                                                                                      multiParamPathParamParametersQueryStatus = multiParamPathParamParametersQueryStatus}
-- | Defines the enum schema located at @paths.\/pet\/multiparam2\/{status}.GET.parameters.properties.pathStatus@ in the specification.
-- 
-- Represents the parameter named \'status\'
-- 
-- Status in path (from path params)
data MultiParamPathParamParametersPathStatus =
   MultiParamPathParamParametersPathStatusOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | MultiParamPathParamParametersPathStatusTyped GHC.Types.Int -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | MultiParamPathParamParametersPathStatusEnum1 -- ^ Represents the JSON value @1@
  | MultiParamPathParamParametersPathStatusEnum3 -- ^ Represents the JSON value @3@
  | MultiParamPathParamParametersPathStatusEnum5 -- ^ Represents the JSON value @5@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON MultiParamPathParamParametersPathStatus
    where {toJSON (MultiParamPathParamParametersPathStatusOther val) = val;
           toJSON (MultiParamPathParamParametersPathStatusTyped val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (MultiParamPathParamParametersPathStatusEnum1) = Data.Aeson.Types.Internal.Number (Data.Scientific.scientific 1 0);
           toJSON (MultiParamPathParamParametersPathStatusEnum3) = Data.Aeson.Types.Internal.Number (Data.Scientific.scientific 3 0);
           toJSON (MultiParamPathParamParametersPathStatusEnum5) = Data.Aeson.Types.Internal.Number (Data.Scientific.scientific 5 0)}
instance Data.Aeson.Types.FromJSON.FromJSON MultiParamPathParamParametersPathStatus
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== Data.Aeson.Types.Internal.Number (Data.Scientific.scientific 1 0) -> MultiParamPathParamParametersPathStatusEnum1
                                             | val GHC.Classes.== Data.Aeson.Types.Internal.Number (Data.Scientific.scientific 3 0) -> MultiParamPathParamParametersPathStatusEnum3
                                             | val GHC.Classes.== Data.Aeson.Types.Internal.Number (Data.Scientific.scientific 5 0) -> MultiParamPathParamParametersPathStatusEnum5
                                             | GHC.Base.otherwise -> MultiParamPathParamParametersPathStatusOther val)}
-- | Defines the enum schema located at @paths.\/pet\/multiparam2\/{status}.GET.parameters.properties.queryStatus@ in the specification.
-- 
-- Represents the parameter named \'status\'
-- 
-- Status in query
data MultiParamPathParamParametersQueryStatus =
   MultiParamPathParamParametersQueryStatusOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | MultiParamPathParamParametersQueryStatusTyped Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | MultiParamPathParamParametersQueryStatusEnumAvailable -- ^ Represents the JSON value @"available"@
  | MultiParamPathParamParametersQueryStatusEnumPending -- ^ Represents the JSON value @"pending"@
  | MultiParamPathParamParametersQueryStatusEnumSold -- ^ Represents the JSON value @"sold"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON MultiParamPathParamParametersQueryStatus
    where {toJSON (MultiParamPathParamParametersQueryStatusOther val) = val;
           toJSON (MultiParamPathParamParametersQueryStatusTyped val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (MultiParamPathParamParametersQueryStatusEnumAvailable) = "available";
           toJSON (MultiParamPathParamParametersQueryStatusEnumPending) = "pending";
           toJSON (MultiParamPathParamParametersQueryStatusEnumSold) = "sold"}
instance Data.Aeson.Types.FromJSON.FromJSON MultiParamPathParamParametersQueryStatus
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "available" -> MultiParamPathParamParametersQueryStatusEnumAvailable
                                             | val GHC.Classes.== "pending" -> MultiParamPathParamParametersQueryStatusEnumPending
                                             | val GHC.Classes.== "sold" -> MultiParamPathParamParametersQueryStatusEnumSold
                                             | GHC.Base.otherwise -> MultiParamPathParamParametersQueryStatusOther val)}
-- | Represents a response of the operation 'multiParamPathParam'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'MultiParamPathParamResponseError' is used.
data MultiParamPathParamResponse =
   MultiParamPathParamResponseError GHC.Base.String -- ^ Means either no matching case available or a parse error
  | MultiParamPathParamResponse200 Dog -- ^ successful operation
  deriving (GHC.Show.Show, GHC.Classes.Eq)
-- | > GET /pet/multiparam2/{status}
-- 
-- The same as 'multiParamPathParam' but accepts an explicit configuration.
multiParamPathParamWithConfiguration :: forall m . OpenAPI.Common.MonadHTTP m => OpenAPI.Common.Configuration -- ^ The configuration to use in the request
  -> MultiParamPathParamParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response MultiParamPathParamResponse) -- ^ Monadic computation which returns the result of the operation
multiParamPathParamWithConfiguration config
                                     parameters = GHC.Base.fmap (\response_2 -> GHC.Base.fmap (Data.Either.either MultiParamPathParamResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> MultiParamPathParamResponse200 Data.Functor.<$> (Data.Aeson.Decoding.eitherDecodeStrict body :: Data.Either.Either GHC.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                            Dog)
                                                                                                                                                                                                | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_2) response_2) (OpenAPI.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Base.$ Data.Text.Internal.pack "GET") ("/pet/multiparam2/" GHC.Base.<> (OpenAPI.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (OpenAPI.Common.textToByte GHC.Base.$ OpenAPI.Common.stringifyModel (multiParamPathParamParametersPathStatus parameters))) GHC.Base.<> "")) [OpenAPI.Common.QueryParameter (Data.Text.Internal.pack "status") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (multiParamPathParamParametersQueryStatus parameters)) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   OpenAPI.Common.QueryParameter (Data.Text.Internal.pack "filter") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> multiParamPathParamParametersQueryFilter parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   OpenAPI.Common.QueryParameter (Data.Text.Internal.pack "referenceParameter") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (multiParamPathParamParametersQueryReferenceParameter parameters)) (Data.Text.Internal.pack "form") GHC.Types.False])
-- | > GET /pet/multiparam2/{status}
-- 
-- The same as 'multiParamPathParam' but returns the raw 'Data.ByteString.ByteString'.
multiParamPathParamRaw :: forall m . OpenAPI.Common.MonadHTTP m => MultiParamPathParamParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> OpenAPI.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
multiParamPathParamRaw parameters = GHC.Base.id (OpenAPI.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.Internal.pack "GET") ("/pet/multiparam2/" GHC.Base.<> (OpenAPI.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (OpenAPI.Common.textToByte GHC.Base.$ OpenAPI.Common.stringifyModel (multiParamPathParamParametersPathStatus parameters))) GHC.Base.<> "")) [OpenAPI.Common.QueryParameter (Data.Text.Internal.pack "status") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (multiParamPathParamParametersQueryStatus parameters)) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                           OpenAPI.Common.QueryParameter (Data.Text.Internal.pack "filter") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> multiParamPathParamParametersQueryFilter parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                           OpenAPI.Common.QueryParameter (Data.Text.Internal.pack "referenceParameter") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (multiParamPathParamParametersQueryReferenceParameter parameters)) (Data.Text.Internal.pack "form") GHC.Types.False])
-- | > GET /pet/multiparam2/{status}
-- 
-- The same as 'multiParamPathParam' but accepts an explicit configuration and returns the raw 'Data.ByteString.ByteString'.
multiParamPathParamWithConfigurationRaw :: forall m . OpenAPI.Common.MonadHTTP m => OpenAPI.Common.Configuration -- ^ The configuration to use in the request
  -> MultiParamPathParamParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString) -- ^ Monadic computation which returns the result of the operation
multiParamPathParamWithConfigurationRaw config
                                        parameters = GHC.Base.id (OpenAPI.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Base.$ Data.Text.Internal.pack "GET") ("/pet/multiparam2/" GHC.Base.<> (OpenAPI.Common.byteToText (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (OpenAPI.Common.textToByte GHC.Base.$ OpenAPI.Common.stringifyModel (multiParamPathParamParametersPathStatus parameters))) GHC.Base.<> "")) [OpenAPI.Common.QueryParameter (Data.Text.Internal.pack "status") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (multiParamPathParamParametersQueryStatus parameters)) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  OpenAPI.Common.QueryParameter (Data.Text.Internal.pack "filter") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> multiParamPathParamParametersQueryFilter parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  OpenAPI.Common.QueryParameter (Data.Text.Internal.pack "referenceParameter") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (multiParamPathParamParametersQueryReferenceParameter parameters)) (Data.Text.Internal.pack "form") GHC.Types.False])
