-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema Gecko
module OpenAPI.Types.Gecko where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified OpenAPI.Common
import OpenAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.Gecko@ in the specification.
-- 
-- 
data Gecko = Gecko {
  -- | hasTail
  geckoHasTail :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | lizardType
  , geckoLizardType :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Gecko
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("hasTail" Data.Aeson.Types.ToJSON..=)) (geckoHasTail obj) : ["lizardType" Data.Aeson.Types.ToJSON..= geckoLizardType obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("hasTail" Data.Aeson.Types.ToJSON..=)) (geckoHasTail obj) : ["lizardType" Data.Aeson.Types.ToJSON..= geckoLizardType obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Gecko
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Gecko" (\obj -> (GHC.Base.pure Gecko GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "hasTail")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "lizardType"))}
-- | Create a new 'Gecko' with all required fields.
mkGecko :: Data.Text.Internal.Text -- ^ 'geckoLizardType'
  -> Gecko
mkGecko geckoLizardType = Gecko{geckoHasTail = GHC.Maybe.Nothing,
                                geckoLizardType = geckoLizardType}
