module OpenAPI.Types.Mischling where
import qualified Data.Aeson
import qualified OpenAPI.Common
data Mischling
instance Show Mischling
instance Eq Mischling
instance Data.Aeson.FromJSON Mischling
instance Data.Aeson.ToJSON Mischling
data MischlingAnother_relativeOneOf5
instance Show MischlingAnother_relativeOneOf5
instance Eq MischlingAnother_relativeOneOf5
instance Data.Aeson.FromJSON MischlingAnother_relativeOneOf5
instance Data.Aeson.ToJSON MischlingAnother_relativeOneOf5
data MischlingAnother_relativeAnother_cat
instance Show MischlingAnother_relativeAnother_cat
instance Eq MischlingAnother_relativeAnother_cat
instance Data.Aeson.FromJSON MischlingAnother_relativeAnother_cat
instance Data.Aeson.ToJSON MischlingAnother_relativeAnother_cat
data MischlingAnother_relativeVariants
instance Show MischlingAnother_relativeVariants
instance Eq MischlingAnother_relativeVariants
instance Data.Aeson.FromJSON MischlingAnother_relativeVariants
instance Data.Aeson.ToJSON MischlingAnother_relativeVariants
data MischlingBreed
instance Show MischlingBreed
instance Eq MischlingBreed
instance Data.Aeson.FromJSON MischlingBreed
instance Data.Aeson.ToJSON MischlingBreed
data MischlingFirst_relative
instance Show MischlingFirst_relative
instance Eq MischlingFirst_relative
instance Data.Aeson.FromJSON MischlingFirst_relative
instance Data.Aeson.ToJSON MischlingFirst_relative
data MischlingFirst_relativeAnother_relativeVariants
instance Show MischlingFirst_relativeAnother_relativeVariants
instance Eq MischlingFirst_relativeAnother_relativeVariants
instance Data.Aeson.FromJSON MischlingFirst_relativeAnother_relativeVariants
instance Data.Aeson.ToJSON MischlingFirst_relativeAnother_relativeVariants
data MischlingFirst_relativePet_type
instance Show MischlingFirst_relativePet_type
instance Eq MischlingFirst_relativePet_type
instance Data.Aeson.FromJSON MischlingFirst_relativePet_type
instance Data.Aeson.ToJSON MischlingFirst_relativePet_type
data MischlingFirst_relativeRelativeVariants
instance Show MischlingFirst_relativeRelativeVariants
instance Eq MischlingFirst_relativeRelativeVariants
instance Data.Aeson.FromJSON MischlingFirst_relativeRelativeVariants
instance Data.Aeson.ToJSON MischlingFirst_relativeRelativeVariants
data MischlingRelativeVariants
instance Show MischlingRelativeVariants
instance Eq MischlingRelativeVariants
instance Data.Aeson.FromJSON MischlingRelativeVariants
instance Data.Aeson.ToJSON MischlingRelativeVariants
