-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema PetByAge
module OpenAPI.Types.PetByAge where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified OpenAPI.Common
import OpenAPI.TypeAlias
import {-# SOURCE #-} OpenAPI.Types.Cat
import {-# SOURCE #-} OpenAPI.Types.PetByType

-- | Defines the object schema located at @components.schemas.PetByAge@ in the specification.
-- 
-- 
data PetByAge = PetByAge {
  -- | age
  petByAgeAge :: GHC.Types.Int
  -- | another_relative
  , petByAgeAnother_relative :: (GHC.Internal.Maybe.Maybe PetByAgeAnother_relativeVariants)
  -- | first_relative
  , petByAgeFirst_relative :: (GHC.Internal.Maybe.Maybe PetByAgeFirst_relative)
  -- | nickname
  , petByAgeNickname :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  -- | relative
  , petByAgeRelative :: (GHC.Internal.Maybe.Maybe PetByAgeRelativeVariants)
  } deriving (GHC.Internal.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PetByAge
    where {toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (["age" Data.Aeson.Types.ToJSON..= petByAgeAge obj] : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("another_relative" Data.Aeson.Types.ToJSON..=)) (petByAgeAnother_relative obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("first_relative" Data.Aeson.Types.ToJSON..=)) (petByAgeFirst_relative obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("nickname" Data.Aeson.Types.ToJSON..=)) (petByAgeNickname obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("relative" Data.Aeson.Types.ToJSON..=)) (petByAgeRelative obj) : GHC.Internal.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (["age" Data.Aeson.Types.ToJSON..= petByAgeAge obj] : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("another_relative" Data.Aeson.Types.ToJSON..=)) (petByAgeAnother_relative obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("first_relative" Data.Aeson.Types.ToJSON..=)) (petByAgeFirst_relative obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("nickname" Data.Aeson.Types.ToJSON..=)) (petByAgeNickname obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("relative" Data.Aeson.Types.ToJSON..=)) (petByAgeRelative obj) : GHC.Internal.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON PetByAge
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "PetByAge" (\obj -> ((((GHC.Internal.Base.pure PetByAge GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..: "age")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "another_relative")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "first_relative")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "nickname")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "relative"))}
-- | Create a new 'PetByAge' with all required fields.
mkPetByAge :: GHC.Types.Int -- ^ 'petByAgeAge'
  -> PetByAge
mkPetByAge petByAgeAge = PetByAge{petByAgeAge = petByAgeAge,
                                  petByAgeAnother_relative = GHC.Internal.Maybe.Nothing,
                                  petByAgeFirst_relative = GHC.Internal.Maybe.Nothing,
                                  petByAgeNickname = GHC.Internal.Maybe.Nothing,
                                  petByAgeRelative = GHC.Internal.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.PetByAge.properties.another_relative.oneOf@ in the specification.
-- 
-- 
data PetByAgeAnother_relativeOneOf5 = PetByAgeAnother_relativeOneOf5 {
  -- | hunts
  petByAgeAnother_relativeOneOf5Hunts :: (GHC.Internal.Maybe.Maybe GHC.Types.Bool)
  -- | pet_type
  , petByAgeAnother_relativeOneOf5Pet_type :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Internal.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PetByAgeAnother_relativeOneOf5
    where {toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("hunts" Data.Aeson.Types.ToJSON..=)) (petByAgeAnother_relativeOneOf5Hunts obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("pet_type" Data.Aeson.Types.ToJSON..=)) (petByAgeAnother_relativeOneOf5Pet_type obj) : GHC.Internal.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("hunts" Data.Aeson.Types.ToJSON..=)) (petByAgeAnother_relativeOneOf5Hunts obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("pet_type" Data.Aeson.Types.ToJSON..=)) (petByAgeAnother_relativeOneOf5Pet_type obj) : GHC.Internal.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON PetByAgeAnother_relativeOneOf5
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "PetByAgeAnother_relativeOneOf5" (\obj -> (GHC.Internal.Base.pure PetByAgeAnother_relativeOneOf5 GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "hunts")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "pet_type"))}
-- | Create a new 'PetByAgeAnother_relativeOneOf5' with all required fields.
mkPetByAgeAnother_relativeOneOf5 :: PetByAgeAnother_relativeOneOf5
mkPetByAgeAnother_relativeOneOf5 = PetByAgeAnother_relativeOneOf5{petByAgeAnother_relativeOneOf5Hunts = GHC.Internal.Maybe.Nothing,
                                                                  petByAgeAnother_relativeOneOf5Pet_type = GHC.Internal.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.PetByAge.properties.another_relative.oneOf@ in the specification.
-- 
-- 
data PetByAgeAnother_relativeAnother_cat = PetByAgeAnother_relativeAnother_cat {
  -- | another_cat
  petByAgeAnother_relativeAnother_catAnother_cat :: Cat
  } deriving (GHC.Internal.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PetByAgeAnother_relativeAnother_cat
    where {toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (["another_cat" Data.Aeson.Types.ToJSON..= petByAgeAnother_relativeAnother_catAnother_cat obj] : GHC.Internal.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (["another_cat" Data.Aeson.Types.ToJSON..= petByAgeAnother_relativeAnother_catAnother_cat obj] : GHC.Internal.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON PetByAgeAnother_relativeAnother_cat
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "PetByAgeAnother_relativeAnother_cat" (\obj -> GHC.Internal.Base.pure PetByAgeAnother_relativeAnother_cat GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..: "another_cat"))}
-- | Create a new 'PetByAgeAnother_relativeAnother_cat' with all required fields.
mkPetByAgeAnother_relativeAnother_cat :: Cat -- ^ 'petByAgeAnother_relativeAnother_catAnother_cat'
  -> PetByAgeAnother_relativeAnother_cat
mkPetByAgeAnother_relativeAnother_cat petByAgeAnother_relativeAnother_catAnother_cat = PetByAgeAnother_relativeAnother_cat{petByAgeAnother_relativeAnother_catAnother_cat = petByAgeAnother_relativeAnother_catAnother_cat}
-- | Defines the oneOf schema located at @components.schemas.PetByAge.properties.another_relative.oneOf@ in the specification.
-- 
-- 
data PetByAgeAnother_relativeVariants =
   PetByAgeAnother_relativeEmptyString -- ^ Represents the JSON value @""@
  | PetByAgeAnother_relativeTest -- ^ Represents the JSON value @"test"@
  | PetByAgeAnother_relativeCat Cat
  | PetByAgeAnother_relativePetByType PetByType
  | PetByAgeAnother_relativeText Data.Text.Internal.Text
  | PetByAgeAnother_relativeListTText [Data.Text.Internal.Text]
  | PetByAgeAnother_relativePetByAgeAnother_relativeOneOf5 PetByAgeAnother_relativeOneOf5
  | PetByAgeAnother_relativePetByAgeAnother_relativeAnother_cat PetByAgeAnother_relativeAnother_cat
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PetByAgeAnother_relativeVariants
    where {toJSON (PetByAgeAnother_relativeCat a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PetByAgeAnother_relativePetByType a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PetByAgeAnother_relativeText a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PetByAgeAnother_relativeListTText a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PetByAgeAnother_relativePetByAgeAnother_relativeOneOf5 a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PetByAgeAnother_relativePetByAgeAnother_relativeAnother_cat a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PetByAgeAnother_relativeEmptyString) = "";
           toJSON (PetByAgeAnother_relativeTest) = "test"}
instance Data.Aeson.Types.FromJSON.FromJSON PetByAgeAnother_relativeVariants
    where {parseJSON val = if | val GHC.Classes.== "" -> GHC.Internal.Base.pure PetByAgeAnother_relativeEmptyString
                              | val GHC.Classes.== "test" -> GHC.Internal.Base.pure PetByAgeAnother_relativeTest
                              | GHC.Internal.Base.otherwise -> case (PetByAgeAnother_relativeCat GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> ((PetByAgeAnother_relativePetByType GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> ((PetByAgeAnother_relativeText GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> ((PetByAgeAnother_relativeListTText GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> ((PetByAgeAnother_relativePetByAgeAnother_relativeOneOf5 GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> ((PetByAgeAnother_relativePetByAgeAnother_relativeAnother_cat GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched"))))) of
                                                               {Data.Aeson.Types.Internal.Success a -> GHC.Internal.Base.pure a;
                                                                Data.Aeson.Types.Internal.Error a -> GHC.Internal.Control.Monad.Fail.fail a}}
-- | Defines the object schema located at @components.schemas.PetByAge.properties.first_relative.allOf@ in the specification.
-- 
-- 
data PetByAgeFirst_relative = PetByAgeFirst_relative {
  -- | age
  petByAgeFirst_relativeAge :: (GHC.Internal.Maybe.Maybe GHC.Types.Int)
  -- | another_relative
  , petByAgeFirst_relativeAnother_relative :: (GHC.Internal.Maybe.Maybe PetByAgeFirst_relativeAnother_relativeVariants)
  -- | hunts
  , petByAgeFirst_relativeHunts :: (GHC.Internal.Maybe.Maybe GHC.Types.Bool)
  -- | pet_type
  , petByAgeFirst_relativePet_type :: PetByAgeFirst_relativePet_type
  -- | relative
  , petByAgeFirst_relativeRelative :: (GHC.Internal.Maybe.Maybe PetByAgeFirst_relativeRelativeVariants)
  } deriving (GHC.Internal.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PetByAgeFirst_relative
    where {toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("age" Data.Aeson.Types.ToJSON..=)) (petByAgeFirst_relativeAge obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("another_relative" Data.Aeson.Types.ToJSON..=)) (petByAgeFirst_relativeAnother_relative obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("hunts" Data.Aeson.Types.ToJSON..=)) (petByAgeFirst_relativeHunts obj) : ["pet_type" Data.Aeson.Types.ToJSON..= petByAgeFirst_relativePet_type obj] : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("relative" Data.Aeson.Types.ToJSON..=)) (petByAgeFirst_relativeRelative obj) : GHC.Internal.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("age" Data.Aeson.Types.ToJSON..=)) (petByAgeFirst_relativeAge obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("another_relative" Data.Aeson.Types.ToJSON..=)) (petByAgeFirst_relativeAnother_relative obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("hunts" Data.Aeson.Types.ToJSON..=)) (petByAgeFirst_relativeHunts obj) : ["pet_type" Data.Aeson.Types.ToJSON..= petByAgeFirst_relativePet_type obj] : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("relative" Data.Aeson.Types.ToJSON..=)) (petByAgeFirst_relativeRelative obj) : GHC.Internal.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON PetByAgeFirst_relative
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "PetByAgeFirst_relative" (\obj -> ((((GHC.Internal.Base.pure PetByAgeFirst_relative GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "age")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "another_relative")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "hunts")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pet_type")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "relative"))}
-- | Create a new 'PetByAgeFirst_relative' with all required fields.
mkPetByAgeFirst_relative :: PetByAgeFirst_relativePet_type -- ^ 'petByAgeFirst_relativePet_type'
  -> PetByAgeFirst_relative
mkPetByAgeFirst_relative petByAgeFirst_relativePet_type = PetByAgeFirst_relative{petByAgeFirst_relativeAge = GHC.Internal.Maybe.Nothing,
                                                                                 petByAgeFirst_relativeAnother_relative = GHC.Internal.Maybe.Nothing,
                                                                                 petByAgeFirst_relativeHunts = GHC.Internal.Maybe.Nothing,
                                                                                 petByAgeFirst_relativePet_type = petByAgeFirst_relativePet_type,
                                                                                 petByAgeFirst_relativeRelative = GHC.Internal.Maybe.Nothing}
-- | Defines the oneOf schema located at @components.schemas.PetByAge.properties.first_relative.allOf.properties.another_relative.oneOf@ in the specification.
-- 
-- 
data PetByAgeFirst_relativeAnother_relativeVariants =
   PetByAgeFirst_relativeAnother_relativeCat Cat
  | PetByAgeFirst_relativeAnother_relativePetByType PetByType
  | PetByAgeFirst_relativeAnother_relativeText Data.Text.Internal.Text
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PetByAgeFirst_relativeAnother_relativeVariants
    where {toJSON (PetByAgeFirst_relativeAnother_relativeCat a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PetByAgeFirst_relativeAnother_relativePetByType a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PetByAgeFirst_relativeAnother_relativeText a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON PetByAgeFirst_relativeAnother_relativeVariants
    where {parseJSON val = case (PetByAgeFirst_relativeAnother_relativeCat GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> ((PetByAgeFirst_relativeAnother_relativePetByType GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> ((PetByAgeFirst_relativeAnother_relativeText GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched")) of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Internal.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> GHC.Internal.Control.Monad.Fail.fail a}}
-- | Defines the enum schema located at @components.schemas.PetByAge.properties.first_relative.allOf.properties.pet_type@ in the specification.
-- 
-- 
data PetByAgeFirst_relativePet_type =
   PetByAgeFirst_relativePet_typeOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | PetByAgeFirst_relativePet_typeTyped Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | PetByAgeFirst_relativePet_typeEnumCat -- ^ Represents the JSON value @"Cat"@
  | PetByAgeFirst_relativePet_typeEnumDog -- ^ Represents the JSON value @"Dog"@
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PetByAgeFirst_relativePet_type
    where {toJSON (PetByAgeFirst_relativePet_typeOther val) = val;
           toJSON (PetByAgeFirst_relativePet_typeTyped val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (PetByAgeFirst_relativePet_typeEnumCat) = "Cat";
           toJSON (PetByAgeFirst_relativePet_typeEnumDog) = "Dog"}
instance Data.Aeson.Types.FromJSON.FromJSON PetByAgeFirst_relativePet_type
    where {parseJSON val = GHC.Internal.Base.pure (if | val GHC.Classes.== "Cat" -> PetByAgeFirst_relativePet_typeEnumCat
                                                      | val GHC.Classes.== "Dog" -> PetByAgeFirst_relativePet_typeEnumDog
                                                      | GHC.Internal.Base.otherwise -> PetByAgeFirst_relativePet_typeOther val)}
-- | Defines the oneOf schema located at @components.schemas.PetByAge.properties.first_relative.allOf.properties.relative.anyOf@ in the specification.
-- 
-- 
data PetByAgeFirst_relativeRelativeVariants =
   PetByAgeFirst_relativeRelativeCat Cat
  | PetByAgeFirst_relativeRelativePetByType PetByType
  | PetByAgeFirst_relativeRelativeText Data.Text.Internal.Text
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PetByAgeFirst_relativeRelativeVariants
    where {toJSON (PetByAgeFirst_relativeRelativeCat a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PetByAgeFirst_relativeRelativePetByType a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PetByAgeFirst_relativeRelativeText a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON PetByAgeFirst_relativeRelativeVariants
    where {parseJSON val = case (PetByAgeFirst_relativeRelativeCat GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> ((PetByAgeFirst_relativeRelativePetByType GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> ((PetByAgeFirst_relativeRelativeText GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched")) of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Internal.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> GHC.Internal.Control.Monad.Fail.fail a}}
-- | Defines the oneOf schema located at @components.schemas.PetByAge.properties.relative.anyOf@ in the specification.
-- 
-- 
data PetByAgeRelativeVariants =
   PetByAgeRelativeCat Cat
  | PetByAgeRelativePetByType PetByType
  | PetByAgeRelativeText Data.Text.Internal.Text
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PetByAgeRelativeVariants
    where {toJSON (PetByAgeRelativeCat a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PetByAgeRelativePetByType a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (PetByAgeRelativeText a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON PetByAgeRelativeVariants
    where {parseJSON val = case (PetByAgeRelativeCat GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> ((PetByAgeRelativePetByType GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> ((PetByAgeRelativeText GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched")) of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Internal.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> GHC.Internal.Control.Monad.Fail.fail a}}
