module OpenAPI.Types.PetByAge where
import qualified Data.Aeson
import qualified OpenAPI.Common
data PetByAge
instance Show PetByAge
instance Eq PetByAge
instance Data.Aeson.FromJSON PetByAge
instance Data.Aeson.ToJSON PetByAge
data PetByAgeAnother_relativeOneOf5
instance Show PetByAgeAnother_relativeOneOf5
instance Eq PetByAgeAnother_relativeOneOf5
instance Data.Aeson.FromJSON PetByAgeAnother_relativeOneOf5
instance Data.Aeson.ToJSON PetByAgeAnother_relativeOneOf5
data PetByAgeAnother_relativeVariants
instance Show PetByAgeAnother_relativeVariants
instance Eq PetByAgeAnother_relativeVariants
instance Data.Aeson.FromJSON PetByAgeAnother_relativeVariants
instance Data.Aeson.ToJSON PetByAgeAnother_relativeVariants
data PetByAgeFirst_relative
instance Show PetByAgeFirst_relative
instance Eq PetByAgeFirst_relative
instance Data.Aeson.FromJSON PetByAgeFirst_relative
instance Data.Aeson.ToJSON PetByAgeFirst_relative
data PetByAgeFirst_relativeAnother_relativeVariants
instance Show PetByAgeFirst_relativeAnother_relativeVariants
instance Eq PetByAgeFirst_relativeAnother_relativeVariants
instance Data.Aeson.FromJSON PetByAgeFirst_relativeAnother_relativeVariants
instance Data.Aeson.ToJSON PetByAgeFirst_relativeAnother_relativeVariants
data PetByAgeFirst_relativePet_type
instance Show PetByAgeFirst_relativePet_type
instance Eq PetByAgeFirst_relativePet_type
instance Data.Aeson.FromJSON PetByAgeFirst_relativePet_type
instance Data.Aeson.ToJSON PetByAgeFirst_relativePet_type
data PetByAgeFirst_relativeRelativeVariants
instance Show PetByAgeFirst_relativeRelativeVariants
instance Eq PetByAgeFirst_relativeRelativeVariants
instance Data.Aeson.FromJSON PetByAgeFirst_relativeRelativeVariants
instance Data.Aeson.ToJSON PetByAgeFirst_relativeRelativeVariants
data PetByAgeRelativeVariants
instance Show PetByAgeRelativeVariants
instance Eq PetByAgeRelativeVariants
instance Data.Aeson.FromJSON PetByAgeRelativeVariants
instance Data.Aeson.ToJSON PetByAgeRelativeVariants
