-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema Shark
module OpenAPI.Types.Shark where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified OpenAPI.Common
import OpenAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.Shark@ in the specification.
-- 
-- 
data Shark = Shark {
  -- | fishType
  sharkFishType :: Data.Text.Internal.Text
  -- | teethRemaining
  , sharkTeethRemaining :: (GHC.Maybe.Maybe GHC.Types.Int)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Shark
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["fishType" Data.Aeson.Types.ToJSON..= sharkFishType obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("teethRemaining" Data.Aeson.Types.ToJSON..=)) (sharkTeethRemaining obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["fishType" Data.Aeson.Types.ToJSON..= sharkFishType obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("teethRemaining" Data.Aeson.Types.ToJSON..=)) (sharkTeethRemaining obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Shark
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Shark" (\obj -> (GHC.Base.pure Shark GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "fishType")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "teethRemaining"))}
-- | Create a new 'Shark' with all required fields.
mkShark :: Data.Text.Internal.Text -- ^ 'sharkFishType'
  -> Shark
mkShark sharkFishType = Shark{sharkFishType = sharkFishType,
                              sharkTeethRemaining = GHC.Maybe.Nothing}
