#!/usr/bin/env bash

set -e

actualDir=actual
expectedDir=expected

[[ -d /root/.stack/snapshots/x86_64-linux/d2f1d79601122b1003c68e260f770c1d32d5fe7a028973b8192e738556d0b8b3 ]] && cp -Rn /root/.stack/snapshots/x86_64-linux/d2f1d79601122b1003c68e260f770c1d32d5fe7a028973b8192e738556d0b8b3 /root/.stack/snapshots/x86_64-linux/711b0e993dd52035c0641daec2c20681935ad613e80e3462008d52395107852b || true
GENERATOR_EXE=$(stack path --local-install-root)/bin/openapi3-code-generator-exe
cd .circleci/golden

specification=z_complex_self_made_example.yml

if [[ $1 == "update" ]]; then
  echo "Update expected directory"
  printf "\n-------------------------\n\n"
  $GENERATOR_EXE "../specifications/$specification" --output-dir=$expectedDir --force
else 
  $GENERATOR_EXE "../specifications/$specification" --output-dir=$actualDir --force
  printf "\n-------------------------\n\n"
  diff -r $actualDir $expectedDir
fi

printf "\n-------------------------\n\n"
