module OpenAPI.Types.PetByAge where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAPI.Common
data PetByAge
instance Show PetByAge
instance Eq PetByAge
instance FromJSON PetByAge
instance ToJSON PetByAge
data PetByAgeAnother_relativeOneOf5
instance Show PetByAgeAnother_relativeOneOf5
instance Eq PetByAgeAnother_relativeOneOf5
instance FromJSON PetByAgeAnother_relativeOneOf5
instance ToJSON PetByAgeAnother_relativeOneOf5
data PetByAgeAnother_relativeVariants
instance Show PetByAgeAnother_relativeVariants
instance Eq PetByAgeAnother_relativeVariants
instance FromJSON PetByAgeAnother_relativeVariants
instance ToJSON PetByAgeAnother_relativeVariants
data PetByAgeFirst_relative
instance Show PetByAgeFirst_relative
instance Eq PetByAgeFirst_relative
instance FromJSON PetByAgeFirst_relative
instance ToJSON PetByAgeFirst_relative
data PetByAgeFirst_relativeAnother_relativeVariants
instance Show PetByAgeFirst_relativeAnother_relativeVariants
instance Eq PetByAgeFirst_relativeAnother_relativeVariants
instance FromJSON PetByAgeFirst_relativeAnother_relativeVariants
instance ToJSON PetByAgeFirst_relativeAnother_relativeVariants
data PetByAgeFirst_relativePet_type
instance Show PetByAgeFirst_relativePet_type
instance Eq PetByAgeFirst_relativePet_type
instance FromJSON PetByAgeFirst_relativePet_type
instance ToJSON PetByAgeFirst_relativePet_type
data PetByAgeFirst_relativeRelativeVariants
instance Show PetByAgeFirst_relativeRelativeVariants
instance Eq PetByAgeFirst_relativeRelativeVariants
instance FromJSON PetByAgeFirst_relativeRelativeVariants
instance ToJSON PetByAgeFirst_relativeRelativeVariants
data PetByAgeRelativeVariants
instance Show PetByAgeRelativeVariants
instance Eq PetByAgeRelativeVariants
instance FromJSON PetByAgeRelativeVariants
instance ToJSON PetByAgeRelativeVariants
