name:                openapi3-code-generator
version:             0.1.0.6
github:              "Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator"
author:              "Remo Dörig & Joel Fisch"
synopsis:            OpenAPI3 Haskell Client Code Generator
category:            Code-Generator
license:             MIT
license-file:        LICENSE
maintainer:          Joel Fisch <joel.fisch96@gmail.com> & Remo Dörig <remo.doerig@gmail.com>
copyright:           "2020 Remo Dörig & Joel Fisch"

extra-source-files:
- LICENSE

description:         Please see the README on GitHub at <https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- yaml
- aeson
- text
- containers
- http-conduit
- http-client
- http-types
- bytestring
- split
- unordered-containers
- scientific
- mtl
- transformers
- time
- optparse-applicative
- vector
- hashmap
- directory
- filepath

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  openapi3-code-generator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - openapi3-code-generator

tests:
  openapi3-code-generator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - openapi3-code-generator
    - hspec
    - genvalidity
    - genvalidity-text
    - genvalidity-hspec
    - validity
    - validity-text
    - QuickCheck
