-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains all types with cyclic dependencies (between each other or to itself)
module OpenAPI.TypeAlias where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified OpenAPI.Common
import {-# SOURCE #-} OpenAPI.Types.Dog


-- | Defines an alias for the schema located at @components.schemas.Test5@ in the specification.
-- 
-- 
type Test5 = [Dog]

-- | Defines an alias for the schema located at @components.schemas.Test4@ in the specification.
-- 
-- 
type Test4 = [Test2]

-- | Defines an alias for the schema located at @components.schemas.Test3@ in the specification.
-- 
-- No properties
type Test3 = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.Test2@ in the specification.
-- 
-- 
type Test2 = [Data.Text.Internal.Text]

-- | Defines an alias for the schema located at @components.schemas.Test10@ in the specification.
-- 
-- 
type Test10 = GHC.Base.NonEmpty Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.Test@ in the specification.
-- 
-- 
type Test = Data.Text.Internal.Text
