-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema ApiResponse
module OpenAPI.Types.ApiResponse where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified OpenAPI.Common
import OpenAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.ApiResponse@ in the specification.
-- 
-- 
data ApiResponse = ApiResponse {
  -- | code
  apiResponseCode :: (GHC.Internal.Maybe.Maybe GHC.Internal.Int.Int32)
  -- | message
  , apiResponseMessage :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  -- | type
  , apiResponseType :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Internal.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON ApiResponse
    where {toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("code" Data.Aeson.Types.ToJSON..=)) (apiResponseCode obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("message" Data.Aeson.Types.ToJSON..=)) (apiResponseMessage obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (apiResponseType obj) : GHC.Internal.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("code" Data.Aeson.Types.ToJSON..=)) (apiResponseCode obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("message" Data.Aeson.Types.ToJSON..=)) (apiResponseMessage obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (apiResponseType obj) : GHC.Internal.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON ApiResponse
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "ApiResponse" (\obj -> ((GHC.Internal.Base.pure ApiResponse GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "code")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "message")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "type"))}
-- | Create a new 'ApiResponse' with all required fields.
mkApiResponse :: ApiResponse
mkApiResponse = ApiResponse{apiResponseCode = GHC.Internal.Maybe.Nothing,
                            apiResponseMessage = GHC.Internal.Maybe.Nothing,
                            apiResponseType = GHC.Internal.Maybe.Nothing}
