-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema User
module OpenAPI.Types.User where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified OpenAPI.Common
import OpenAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.User@ in the specification.
-- 
-- 
data User = User {
  -- | email
  userEmail :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | firstName
  , userFirstName :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | id
  , userId :: (GHC.Maybe.Maybe GHC.Int.Int64)
  -- | lastName
  , userLastName :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | password
  , userPassword :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | phone
  , userPhone :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | userStatus: User Status
  , userUserStatus :: (GHC.Maybe.Maybe GHC.Int.Int32)
  -- | username
  , userUsername :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON User
    where toJSON obj = Data.Aeson.Types.Internal.object ("email" Data.Aeson.Types.ToJSON..= userEmail obj : "firstName" Data.Aeson.Types.ToJSON..= userFirstName obj : "id" Data.Aeson.Types.ToJSON..= userId obj : "lastName" Data.Aeson.Types.ToJSON..= userLastName obj : "password" Data.Aeson.Types.ToJSON..= userPassword obj : "phone" Data.Aeson.Types.ToJSON..= userPhone obj : "userStatus" Data.Aeson.Types.ToJSON..= userUserStatus obj : "username" Data.Aeson.Types.ToJSON..= userUsername obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("email" Data.Aeson.Types.ToJSON..= userEmail obj) GHC.Base.<> (("firstName" Data.Aeson.Types.ToJSON..= userFirstName obj) GHC.Base.<> (("id" Data.Aeson.Types.ToJSON..= userId obj) GHC.Base.<> (("lastName" Data.Aeson.Types.ToJSON..= userLastName obj) GHC.Base.<> (("password" Data.Aeson.Types.ToJSON..= userPassword obj) GHC.Base.<> (("phone" Data.Aeson.Types.ToJSON..= userPhone obj) GHC.Base.<> (("userStatus" Data.Aeson.Types.ToJSON..= userUserStatus obj) GHC.Base.<> ("username" Data.Aeson.Types.ToJSON..= userUsername obj))))))))
instance Data.Aeson.Types.FromJSON.FromJSON User
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "User" (\obj -> (((((((GHC.Base.pure User GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "email")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "firstName")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "lastName")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "password")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "phone")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "userStatus")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "username"))
-- | Create a new 'User' with all required fields.
mkUser :: User
mkUser = User{userEmail = GHC.Maybe.Nothing,
              userFirstName = GHC.Maybe.Nothing,
              userId = GHC.Maybe.Nothing,
              userLastName = GHC.Maybe.Nothing,
              userPassword = GHC.Maybe.Nothing,
              userPhone = GHC.Maybe.Nothing,
              userUserStatus = GHC.Maybe.Nothing,
              userUsername = GHC.Maybe.Nothing}
