-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema User
module OpenAPI.Types.User where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified OpenAPI.Common
import OpenAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.User@ in the specification.
-- 
-- 
data User = User {
  -- | email
  userEmail :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  -- | firstName
  , userFirstName :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  -- | id
  , userId :: (GHC.Internal.Maybe.Maybe GHC.Internal.Int.Int64)
  -- | lastName
  , userLastName :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  -- | password
  , userPassword :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  -- | phone
  , userPhone :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  -- | userStatus: User Status
  , userUserStatus :: (GHC.Internal.Maybe.Maybe GHC.Internal.Int.Int32)
  -- | username
  , userUsername :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Internal.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON User
    where {toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("email" Data.Aeson.Types.ToJSON..=)) (userEmail obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("firstName" Data.Aeson.Types.ToJSON..=)) (userFirstName obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("id" Data.Aeson.Types.ToJSON..=)) (userId obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("lastName" Data.Aeson.Types.ToJSON..=)) (userLastName obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("password" Data.Aeson.Types.ToJSON..=)) (userPassword obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("phone" Data.Aeson.Types.ToJSON..=)) (userPhone obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("userStatus" Data.Aeson.Types.ToJSON..=)) (userUserStatus obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("username" Data.Aeson.Types.ToJSON..=)) (userUsername obj) : GHC.Internal.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("email" Data.Aeson.Types.ToJSON..=)) (userEmail obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("firstName" Data.Aeson.Types.ToJSON..=)) (userFirstName obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("id" Data.Aeson.Types.ToJSON..=)) (userId obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("lastName" Data.Aeson.Types.ToJSON..=)) (userLastName obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("password" Data.Aeson.Types.ToJSON..=)) (userPassword obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("phone" Data.Aeson.Types.ToJSON..=)) (userPhone obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("userStatus" Data.Aeson.Types.ToJSON..=)) (userUserStatus obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("username" Data.Aeson.Types.ToJSON..=)) (userUsername obj) : GHC.Internal.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON User
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "User" (\obj -> (((((((GHC.Internal.Base.pure User GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "email")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "firstName")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "id")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "lastName")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "password")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "phone")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "userStatus")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "username"))}
-- | Create a new 'User' with all required fields.
mkUser :: User
mkUser = User{userEmail = GHC.Internal.Maybe.Nothing,
              userFirstName = GHC.Internal.Maybe.Nothing,
              userId = GHC.Internal.Maybe.Nothing,
              userLastName = GHC.Internal.Maybe.Nothing,
              userPassword = GHC.Internal.Maybe.Nothing,
              userPhone = GHC.Internal.Maybe.Nothing,
              userUserStatus = GHC.Internal.Maybe.Nothing,
              userUsername = GHC.Internal.Maybe.Nothing}
